In [2]:
import numpy as np

In [3]:
a = [1,2,3,4,5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [4]:
print(type(b))

<class 'numpy.ndarray'>


In [5]:
c = np.array(a * 5)
c

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5])

In [6]:
d = np.ones(5, dtype = int)
d

array([1, 1, 1, 1, 1])

In [8]:
e = np.zeros(5, dtype = int)
e

array([0, 0, 0, 0, 0])

In [10]:
f = np.zeros((3,3), dtype = int)
f

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
g = np.full((2,2), 100, dtype = int)
g

array([[100, 100],
       [100, 100]])

In [12]:
h = np.empty((2,2))
h
# np.empty gives random values, but creates an array

array([[3.60286887e+252, 1.63803508e-307],
       [6.04608851e-138, 4.33848671e-313]])

In [14]:
m =  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
n = np.array(m)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
import numpy as np
a = np.zeros(10, dtype = int)
a[4] = 1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [17]:
b = np.arange(100)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
b = np.arange(1, 11, 2, float)
b

array([1., 3., 5., 7., 9.])

In [19]:
b = np.linspace(2,10, 20)
b

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [20]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
b = np.eye(4,5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [23]:
np.random.rand(2,3) * 100

array([[ 3.50167023, 34.75266159, 21.99815497],
       [74.63553996, 87.60069608, 51.11217782]])

In [24]:
np.random.randint(10, 20)

18

### Q. Create an array with values ranging consecutively from 9 to 49 (both inclusive).

In [25]:
import numpy as np
b = np.arange(9,50,1)
print(*b)

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49


### Q. Create an integer identity matrix of size (5, 6).

In [26]:
import numpy as np
b = np.eye(5,6, dtype = int)
print(b)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


### Q.You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
### Note:Round upto 2 decimal place.

In [28]:
import numpy as np
b = np.linspace(0,5,9)
for el in b:
    print(format(el, '.2f'))

0.00
0.62
1.25
1.88
2.50
3.12
3.75
4.38
5.00


In [29]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

for el in input_[2,:3]:
    print(el, end = ' ')
print()
for el in input_[1:,3]:
    print(el, end = ' ')
print()
for row in input_[2:]:
    for el in row:
        print(el, end = ' ')
print()
for row in input_[1:3, 1:3]:
    for el in row:
        print(el, end = ' ')
print()

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 


In [30]:
a = np.random.randint(1,30, 10)
b = np.random.randint(1,30, 10)
a

array([26, 26,  9,  7, 25, 17, 27, 29,  2, 14])

In [31]:
b

array([27, 24, 27, 23,  1, 17, 10, 22,  8, 16])

In [32]:
a + b

array([53, 50, 36, 30, 26, 34, 37, 51, 10, 30])

In [33]:
a * b 

array([702, 624, 243, 161,  25, 289, 270, 638,  16, 224])

In [35]:
a = np.random.randint(1,30,(3,3))
a

array([[19,  1, 19],
       [26, 19,  2],
       [ 1,  5,  5]])

In [36]:
b = np.random.randint(1,30,(3,3))
b

array([[ 3,  2, 15],
       [24, 21, 28],
       [23, 17,  2]])

In [37]:
a + b

array([[22,  3, 34],
       [50, 40, 30],
       [24, 22,  7]])

In [38]:
a ** b

array([[       6859,           1, -1044074789],
       [ 1627389952,   972113667,   268435456],
       [          1, -1564725563,          25]])

In [39]:
a // b

array([[6, 0, 1],
       [1, 0, 0],
       [0, 0, 2]])

In [40]:
np.logical_not(a//b)

array([[False,  True, False],
       [False,  True,  True],
       [ True,  True, False]])

In [41]:
a

array([[19,  1, 19],
       [26, 19,  2],
       [ 1,  5,  5]])

In [42]:
b

array([[ 3,  2, 15],
       [24, 21, 28],
       [23, 17,  2]])

In [43]:
print(a > 10)

[[ True False  True]
 [ True  True False]
 [False False False]]


In [44]:
print(a[a > 10])

[19 19 26 19]


In [45]:
print(np.where(a > 10))

(array([0, 0, 1, 1], dtype=int64), array([0, 2, 0, 1], dtype=int64))


In [46]:
print(b[np.where(a > 10)])

[ 3 15 24 21]


In [47]:
a[1:5] = 99

In [48]:
a

array([[19,  1, 19],
       [99, 99, 99],
       [99, 99, 99]])

In [49]:
print(b[(b > 10) & (b < 18)])

[15 17]


In [50]:
b

array([[ 3,  2, 15],
       [24, 21, 28],
       [23, 17,  2]])

### Find indices of non-zero elements from the array [1,2,0,0,4,0] ?

In [54]:
import numpy as np
a = np.array([1,2,0,0,4,0], dtype = int)
idx = np.where(a > 0)
for el in idx:
    for e2 in el:
        print(e2, end = ' ')

0 1 4 

### Given an integer array of size 10. Print the index of elements which are multiple of 3.

In [56]:
import numpy as np
a = np.array([1,3,5,7,9,11,13,15,17,19], dtype = int)
idx = np.where(a % 3 == 0)
for row in idx:
    for el in row:
        print(el, end =' ')

1 4 7 

### Given an integer array of size 10. Replace the odd number in numpy array with -1

In [57]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = int)
a[a%2 == 1] = -1
print(*a)

-1 2 -1 4 -1 6 -1 8 -1 10


### Given an integer array of size 10 and replace the first occurrence of maximum value by 0

In [60]:
import numpy as np
a = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19], dtype = int)
a[a.argmax()] = 0
print(*a)

11 2 13 4 15 6 0 8 19


### Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?

In [61]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = int)
a[(a>=3) & (a<=8)] = -a[(a>=3) & (a<=8)]
for el in a:
    print(el)

1
2
-3
-4
-5
-6
-7
-8
9
10


### Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.

In [67]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
for row in np.where(height > 155):
    for i in row:
        print(age[i], height[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


### Sort a given 2D array of shape (4, 5), Sort is by 2nd column (i.e. column at index 1) in ascending order.

In [69]:
import numpy as np
a = np.arange(21, 1, -1)
a = np.reshape(a, (4,5))
a = a[a[:,1].argsort()]
print(a)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]
